version: "2"
services:
  web:
    build: .
    command: yarn dev
    volumes:
      - .:/app
      - .:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://main:123456@localhost:5432/tugasguru?schema=public"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "tugasguru"
